apiVersion: v1
kind: Pod
metadata:
  name: strapi-populate
  namespace: secnews
spec:
  restartPolicy: Never
  containers:
  - name: builder
    image: node:18-alpine
    command: ["sh", "-c", "sleep 3600"]
    env:
    - name: DATABASE_CLIENT
      value: postgres
    - name: DATABASE_HOST
      value: postgres.secnewsdb.svc.cluster.local
    - name: DATABASE_PORT
      value: "5432"
    - name: DATABASE_NAME
      valueFrom:
        secretKeyRef:
          name: strapi-secret
          key: DATABASE_NAME
    - name: DATABASE_USERNAME
      valueFrom:
        secretKeyRef:
          name: strapi-secret
          key: DATABASE_USERNAME
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: strapi-secret
          key: DATABASE_PASSWORD
    volumeMounts:
    - name: strapi-storage
      mountPath: /srv/app
  volumes:
  - name: strapi-storage
    persistentVolumeClaim:
      claimName: strapi-pvc
