name: Apply patch from chat

on:
  workflow_dispatch:
    inputs:
      patch:
        description: "Unified diff (.patch) nội dung do ChatGPT cung cấp"
        required: true
        type: string
      base:
        description: "Base branch"
        required: true
        default: "main"

permissions:
  contents: write
  pull-requests: write

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.base }}
          fetch-depth: 0

      - id: vars
        run: echo "branch=chore/apply-patch-${{ github.run_id }}" >> "$GITHUB_OUTPUT"

      - name: Apply patch (3-way)
        shell: bash
        run: |
          set -euo pipefail
          git checkout -b "${{ steps.vars.outputs.branch }}"
          cat > /tmp/changes.patch <<'PATCH'
